server:
  port: 8089

spring:
  application:
    name: APIGATEWAY

  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        discovery-server-url: kubeMasterNodeURL
      service:
        locator:
          enabled: true
